services:
  blogs:
    container_name: blogs
    build:
      context: .
      dockerfile: ./apps/blogs/Dockerfile
      target: development
    command: npm run start:dev blogs
    env_file:
      - ./apps/blogs/.env
    ports:
      - '3004:3004'
    volumes:
      - .:/usr/src/app

  aws:
    container_name: aws
    build:
      context: .
      dockerfile: ./apps/aws/Dockerfile
      target: development
    command: npm run start:dev aws
    env_file:
      - ./apps/aws/.env
    ports:
      - '3005:3005'
    volumes:
      - .:/usr/src/app

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3006:3006'
    volumes:
      - .:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo
    # ports:
    #   - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
